version: "3.9"

services:
  api:
    image: vkarpovich/skypro_hw_26:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 25000:25000
  pg:
    image: postgres:latest
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5